# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from aos.runtime.store import agent_store_pb2 as aos_dot_runtime_dot_store_dot_agent__store__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class AgentStoreStub(object):
    """Manage Agents
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateAgent = channel.unary_unary(
                '/AgentStore/CreateAgent',
                request_serializer=aos_dot_runtime_dot_store_dot_agent__store__pb2.CreateAgentRequest.SerializeToString,
                response_deserializer=aos_dot_runtime_dot_store_dot_agent__store__pb2.CreateAgentResponse.FromString,
                )
        self.DeleteAgent = channel.unary_unary(
                '/AgentStore/DeleteAgent',
                request_serializer=aos_dot_runtime_dot_store_dot_agent__store__pb2.DeleteAgentRequest.SerializeToString,
                response_deserializer=aos_dot_runtime_dot_store_dot_agent__store__pb2.DeleteAgentResponse.FromString,
                )
        self.GetAgent = channel.unary_unary(
                '/AgentStore/GetAgent',
                request_serializer=aos_dot_runtime_dot_store_dot_agent__store__pb2.GetAgentRequest.SerializeToString,
                response_deserializer=aos_dot_runtime_dot_store_dot_agent__store__pb2.GetAgentResponse.FromString,
                )
        self.GetAgents = channel.unary_unary(
                '/AgentStore/GetAgents',
                request_serializer=aos_dot_runtime_dot_store_dot_agent__store__pb2.GetAgentsRequest.SerializeToString,
                response_deserializer=aos_dot_runtime_dot_store_dot_agent__store__pb2.GetAgentsResponse.FromString,
                )
        self.SetVar = channel.unary_unary(
                '/AgentStore/SetVar',
                request_serializer=aos_dot_runtime_dot_store_dot_agent__store__pb2.SetVarRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetVar = channel.unary_unary(
                '/AgentStore/GetVar',
                request_serializer=aos_dot_runtime_dot_store_dot_agent__store__pb2.GetVarRequest.SerializeToString,
                response_deserializer=aos_dot_runtime_dot_store_dot_agent__store__pb2.GetVarResponse.FromString,
                )
        self.GetVars = channel.unary_unary(
                '/AgentStore/GetVars',
                request_serializer=aos_dot_runtime_dot_store_dot_agent__store__pb2.GetVarsRequest.SerializeToString,
                response_deserializer=aos_dot_runtime_dot_store_dot_agent__store__pb2.GetVarsResponse.FromString,
                )
        self.DeleteVar = channel.unary_unary(
                '/AgentStore/DeleteVar',
                request_serializer=aos_dot_runtime_dot_store_dot_agent__store__pb2.DeleteVarRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class AgentStoreServicer(object):
    """Manage Agents
    """

    def CreateAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVars(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteVar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAgent,
                    request_deserializer=aos_dot_runtime_dot_store_dot_agent__store__pb2.CreateAgentRequest.FromString,
                    response_serializer=aos_dot_runtime_dot_store_dot_agent__store__pb2.CreateAgentResponse.SerializeToString,
            ),
            'DeleteAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAgent,
                    request_deserializer=aos_dot_runtime_dot_store_dot_agent__store__pb2.DeleteAgentRequest.FromString,
                    response_serializer=aos_dot_runtime_dot_store_dot_agent__store__pb2.DeleteAgentResponse.SerializeToString,
            ),
            'GetAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgent,
                    request_deserializer=aos_dot_runtime_dot_store_dot_agent__store__pb2.GetAgentRequest.FromString,
                    response_serializer=aos_dot_runtime_dot_store_dot_agent__store__pb2.GetAgentResponse.SerializeToString,
            ),
            'GetAgents': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgents,
                    request_deserializer=aos_dot_runtime_dot_store_dot_agent__store__pb2.GetAgentsRequest.FromString,
                    response_serializer=aos_dot_runtime_dot_store_dot_agent__store__pb2.GetAgentsResponse.SerializeToString,
            ),
            'SetVar': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVar,
                    request_deserializer=aos_dot_runtime_dot_store_dot_agent__store__pb2.SetVarRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetVar': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVar,
                    request_deserializer=aos_dot_runtime_dot_store_dot_agent__store__pb2.GetVarRequest.FromString,
                    response_serializer=aos_dot_runtime_dot_store_dot_agent__store__pb2.GetVarResponse.SerializeToString,
            ),
            'GetVars': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVars,
                    request_deserializer=aos_dot_runtime_dot_store_dot_agent__store__pb2.GetVarsRequest.FromString,
                    response_serializer=aos_dot_runtime_dot_store_dot_agent__store__pb2.GetVarsResponse.SerializeToString,
            ),
            'DeleteVar': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteVar,
                    request_deserializer=aos_dot_runtime_dot_store_dot_agent__store__pb2.DeleteVarRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AgentStore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AgentStore(object):
    """Manage Agents
    """

    @staticmethod
    def CreateAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AgentStore/CreateAgent',
            aos_dot_runtime_dot_store_dot_agent__store__pb2.CreateAgentRequest.SerializeToString,
            aos_dot_runtime_dot_store_dot_agent__store__pb2.CreateAgentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AgentStore/DeleteAgent',
            aos_dot_runtime_dot_store_dot_agent__store__pb2.DeleteAgentRequest.SerializeToString,
            aos_dot_runtime_dot_store_dot_agent__store__pb2.DeleteAgentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AgentStore/GetAgent',
            aos_dot_runtime_dot_store_dot_agent__store__pb2.GetAgentRequest.SerializeToString,
            aos_dot_runtime_dot_store_dot_agent__store__pb2.GetAgentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAgents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AgentStore/GetAgents',
            aos_dot_runtime_dot_store_dot_agent__store__pb2.GetAgentsRequest.SerializeToString,
            aos_dot_runtime_dot_store_dot_agent__store__pb2.GetAgentsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetVar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AgentStore/SetVar',
            aos_dot_runtime_dot_store_dot_agent__store__pb2.SetVarRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AgentStore/GetVar',
            aos_dot_runtime_dot_store_dot_agent__store__pb2.GetVarRequest.SerializeToString,
            aos_dot_runtime_dot_store_dot_agent__store__pb2.GetVarResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVars(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AgentStore/GetVars',
            aos_dot_runtime_dot_store_dot_agent__store__pb2.GetVarsRequest.SerializeToString,
            aos_dot_runtime_dot_store_dot_agent__store__pb2.GetVarsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteVar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AgentStore/DeleteVar',
            aos_dot_runtime_dot_store_dot_agent__store__pb2.DeleteVarRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
