# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from aos.runtime.store import grit_store_pb2 as aos_dot_runtime_dot_store_dot_grit__store__pb2


class GritStoreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Store = channel.unary_unary(
                '/GritStore/Store',
                request_serializer=aos_dot_runtime_dot_store_dot_grit__store__pb2.StoreRequest.SerializeToString,
                response_deserializer=aos_dot_runtime_dot_store_dot_grit__store__pb2.StoreResponse.FromString,
                )
        self.Load = channel.unary_unary(
                '/GritStore/Load',
                request_serializer=aos_dot_runtime_dot_store_dot_grit__store__pb2.LoadRequest.SerializeToString,
                response_deserializer=aos_dot_runtime_dot_store_dot_grit__store__pb2.LoadResponse.FromString,
                )


class GritStoreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Store(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Load(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GritStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Store': grpc.unary_unary_rpc_method_handler(
                    servicer.Store,
                    request_deserializer=aos_dot_runtime_dot_store_dot_grit__store__pb2.StoreRequest.FromString,
                    response_serializer=aos_dot_runtime_dot_store_dot_grit__store__pb2.StoreResponse.SerializeToString,
            ),
            'Load': grpc.unary_unary_rpc_method_handler(
                    servicer.Load,
                    request_deserializer=aos_dot_runtime_dot_store_dot_grit__store__pb2.LoadRequest.FromString,
                    response_serializer=aos_dot_runtime_dot_store_dot_grit__store__pb2.LoadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GritStore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GritStore(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Store(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GritStore/Store',
            aos_dot_runtime_dot_store_dot_grit__store__pb2.StoreRequest.SerializeToString,
            aos_dot_runtime_dot_store_dot_grit__store__pb2.StoreResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Load(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GritStore/Load',
            aos_dot_runtime_dot_store_dot_grit__store__pb2.LoadRequest.SerializeToString,
            aos_dot_runtime_dot_store_dot_grit__store__pb2.LoadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
