# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from aos.runtime.store import secret_store_pb2 as aos_dot_runtime_dot_store_dot_secret__store__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class SecretStoreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetSecret = channel.unary_unary(
                '/SecretStore/SetSecret',
                request_serializer=aos_dot_runtime_dot_store_dot_secret__store__pb2.SetSecretRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetSecret = channel.unary_unary(
                '/SecretStore/GetSecret',
                request_serializer=aos_dot_runtime_dot_store_dot_secret__store__pb2.GetSecretRequest.SerializeToString,
                response_deserializer=aos_dot_runtime_dot_store_dot_secret__store__pb2.GetSecretResponse.FromString,
                )
        self.GetSecrets = channel.unary_unary(
                '/SecretStore/GetSecrets',
                request_serializer=aos_dot_runtime_dot_store_dot_secret__store__pb2.GetSecretsRequest.SerializeToString,
                response_deserializer=aos_dot_runtime_dot_store_dot_secret__store__pb2.GetSecretsResponse.FromString,
                )
        self.DeleteSecret = channel.unary_unary(
                '/SecretStore/DeleteSecret',
                request_serializer=aos_dot_runtime_dot_store_dot_secret__store__pb2.DeleteSecretRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class SecretStoreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetSecret(self, request, context):
        """ref store calls
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSecret(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSecrets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSecret(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SecretStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetSecret': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSecret,
                    request_deserializer=aos_dot_runtime_dot_store_dot_secret__store__pb2.SetSecretRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetSecret': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSecret,
                    request_deserializer=aos_dot_runtime_dot_store_dot_secret__store__pb2.GetSecretRequest.FromString,
                    response_serializer=aos_dot_runtime_dot_store_dot_secret__store__pb2.GetSecretResponse.SerializeToString,
            ),
            'GetSecrets': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSecrets,
                    request_deserializer=aos_dot_runtime_dot_store_dot_secret__store__pb2.GetSecretsRequest.FromString,
                    response_serializer=aos_dot_runtime_dot_store_dot_secret__store__pb2.GetSecretsResponse.SerializeToString,
            ),
            'DeleteSecret': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSecret,
                    request_deserializer=aos_dot_runtime_dot_store_dot_secret__store__pb2.DeleteSecretRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SecretStore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SecretStore(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetSecret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SecretStore/SetSecret',
            aos_dot_runtime_dot_store_dot_secret__store__pb2.SetSecretRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSecret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SecretStore/GetSecret',
            aos_dot_runtime_dot_store_dot_secret__store__pb2.GetSecretRequest.SerializeToString,
            aos_dot_runtime_dot_store_dot_secret__store__pb2.GetSecretResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSecrets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SecretStore/GetSecrets',
            aos_dot_runtime_dot_store_dot_secret__store__pb2.GetSecretsRequest.SerializeToString,
            aos_dot_runtime_dot_store_dot_secret__store__pb2.GetSecretsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteSecret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SecretStore/DeleteSecret',
            aos_dot_runtime_dot_store_dot_secret__store__pb2.DeleteSecretRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
