# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aos/runtime/store/secret_store.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$aos/runtime/store/secret_store.proto\x1a\x1bgoogle/protobuf/empty.proto\"@\n\x10SetSecretRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\x0c\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\"1\n\x10GetSecretRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\x0c\x12\x0b\n\x03key\x18\x02 \x01(\t\"P\n\x11GetSecretResponse\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\x0c\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\x12\n\x05value\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_value\"M\n\x11GetSecretsRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\x0c\x12\x17\n\nkey_prefix\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\r\n\x0b_key_prefix\"\x86\x01\n\x12GetSecretsResponse\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\x0c\x12/\n\x06values\x18\x02 \x03(\x0b\x32\x1f.GetSecretsResponse.ValuesEntry\x1a-\n\x0bValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\"4\n\x13\x44\x65leteSecretRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\x0c\x12\x0b\n\x03key\x18\x02 \x01(\t2\xf6\x01\n\x0bSecretStore\x12\x38\n\tSetSecret\x12\x11.SetSecretRequest\x1a\x16.google.protobuf.Empty\"\x00\x12\x34\n\tGetSecret\x12\x11.GetSecretRequest\x1a\x12.GetSecretResponse\"\x00\x12\x37\n\nGetSecrets\x12\x12.GetSecretsRequest\x1a\x13.GetSecretsResponse\"\x00\x12>\n\x0c\x44\x65leteSecret\x12\x14.DeleteSecretRequest\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aos.runtime.store.secret_store_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETSECRETSRESPONSE_VALUESENTRY']._options = None
  _globals['_GETSECRETSRESPONSE_VALUESENTRY']._serialized_options = b'8\001'
  _globals['_SETSECRETREQUEST']._serialized_start=69
  _globals['_SETSECRETREQUEST']._serialized_end=133
  _globals['_GETSECRETREQUEST']._serialized_start=135
  _globals['_GETSECRETREQUEST']._serialized_end=184
  _globals['_GETSECRETRESPONSE']._serialized_start=186
  _globals['_GETSECRETRESPONSE']._serialized_end=266
  _globals['_GETSECRETSREQUEST']._serialized_start=268
  _globals['_GETSECRETSREQUEST']._serialized_end=345
  _globals['_GETSECRETSRESPONSE']._serialized_start=348
  _globals['_GETSECRETSRESPONSE']._serialized_end=482
  _globals['_GETSECRETSRESPONSE_VALUESENTRY']._serialized_start=437
  _globals['_GETSECRETSRESPONSE_VALUESENTRY']._serialized_end=482
  _globals['_DELETESECRETREQUEST']._serialized_start=484
  _globals['_DELETESECRETREQUEST']._serialized_end=536
  _globals['_SECRETSTORE']._serialized_start=539
  _globals['_SECRETSTORE']._serialized_end=785
# @@protoc_insertion_point(module_scope)
