# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from aos.runtime.apex import apex_workers_pb2 as aos_dot_runtime_dot_apex_dot_apex__workers__pb2


class ApexWorkersStub(object):
    """Internal service for worker nodes to communicate with the Apex node
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterWorker = channel.unary_unary(
                '/ApexWorkers/RegisterWorker',
                request_serializer=aos_dot_runtime_dot_apex_dot_apex__workers__pb2.WorkerRegistrationRequest.SerializeToString,
                response_deserializer=aos_dot_runtime_dot_apex_dot_apex__workers__pb2.WorkerRegistrationResponse.FromString,
                )
        self.ConnectWorker = channel.stream_stream(
                '/ApexWorkers/ConnectWorker',
                request_serializer=aos_dot_runtime_dot_apex_dot_apex__workers__pb2.WorkerToApexMessage.SerializeToString,
                response_deserializer=aos_dot_runtime_dot_apex_dot_apex__workers__pb2.ApexToWorkerMessage.FromString,
                )


class ApexWorkersServicer(object):
    """Internal service for worker nodes to communicate with the Apex node
    """

    def RegisterWorker(self, request, context):
        """Registers a worker to get ready for a streaming connection.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConnectWorker(self, request_iterator, context):
        """Connects a long running worker to the apex node via two-way streaming. Worker needs to register first.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ApexWorkersServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=aos_dot_runtime_dot_apex_dot_apex__workers__pb2.WorkerRegistrationRequest.FromString,
                    response_serializer=aos_dot_runtime_dot_apex_dot_apex__workers__pb2.WorkerRegistrationResponse.SerializeToString,
            ),
            'ConnectWorker': grpc.stream_stream_rpc_method_handler(
                    servicer.ConnectWorker,
                    request_deserializer=aos_dot_runtime_dot_apex_dot_apex__workers__pb2.WorkerToApexMessage.FromString,
                    response_serializer=aos_dot_runtime_dot_apex_dot_apex__workers__pb2.ApexToWorkerMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ApexWorkers', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ApexWorkers(object):
    """Internal service for worker nodes to communicate with the Apex node
    """

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ApexWorkers/RegisterWorker',
            aos_dot_runtime_dot_apex_dot_apex__workers__pb2.WorkerRegistrationRequest.SerializeToString,
            aos_dot_runtime_dot_apex_dot_apex__workers__pb2.WorkerRegistrationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConnectWorker(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/ApexWorkers/ConnectWorker',
            aos_dot_runtime_dot_apex_dot_apex__workers__pb2.WorkerToApexMessage.SerializeToString,
            aos_dot_runtime_dot_apex_dot_apex__workers__pb2.ApexToWorkerMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
