# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aos/runtime/worker/worker_api.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#aos/runtime/worker/worker_api.proto\"\x8b\x01\n\x14InjectMessageRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\x0c\x12\x14\n\x0crecipient_id\x18\x02 \x01(\x0c\x12\x14\n\nmessage_id\x18\x05 \x01(\x0cH\x00\x12*\n\x0cmessage_data\x18\x06 \x01(\x0b\x32\x12.InjectMessageDataH\x00\x42\t\n\x07message\"\xc1\x01\n\x11InjectMessageData\x12\x30\n\x07headers\x18\x03 \x03(\x0b\x32\x1f.InjectMessageData.HeadersEntry\x12\x11\n\tis_signal\x18\x04 \x01(\x08\x12\x14\n\ncontent_id\x18\x05 \x01(\x0cH\x00\x12\x16\n\x0c\x63ontent_blob\x18\x06 \x01(\x0cH\x00\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\t\n\x07\x63ontent\"=\n\x15InjectMessageResponse\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\x0c\x12\x12\n\nmessage_id\x18\x02 \x01(\x0c\"k\n\x0fRunQueryRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\x0c\x12\x10\n\x08\x61\x63tor_id\x18\x02 \x01(\x0c\x12\x12\n\nquery_name\x18\x04 \x01(\t\x12\x14\n\x07\x63ontext\x18\x05 \x01(\x0cH\x00\x88\x01\x01\x42\n\n\x08_context\"}\n\x10RunQueryResponse\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\x0c\x12\x10\n\x08\x61\x63tor_id\x18\x02 \x01(\x0c\x12\x13\n\tobject_id\x18\n \x01(\x0cH\x00\x12\x15\n\x0bobject_blob\x18\x0b \x01(\x0cH\x00\x12\x0f\n\x05\x65rror\x18\x0c \x01(\tH\x00\x42\x08\n\x06result2\x80\x01\n\tWorkerApi\x12@\n\rInjectMessage\x12\x15.InjectMessageRequest\x1a\x16.InjectMessageResponse\"\x00\x12\x31\n\x08RunQuery\x12\x10.RunQueryRequest\x1a\x11.RunQueryResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aos.runtime.worker.worker_api_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INJECTMESSAGEDATA_HEADERSENTRY']._options = None
  _globals['_INJECTMESSAGEDATA_HEADERSENTRY']._serialized_options = b'8\001'
  _globals['_INJECTMESSAGEREQUEST']._serialized_start=40
  _globals['_INJECTMESSAGEREQUEST']._serialized_end=179
  _globals['_INJECTMESSAGEDATA']._serialized_start=182
  _globals['_INJECTMESSAGEDATA']._serialized_end=375
  _globals['_INJECTMESSAGEDATA_HEADERSENTRY']._serialized_start=318
  _globals['_INJECTMESSAGEDATA_HEADERSENTRY']._serialized_end=364
  _globals['_INJECTMESSAGERESPONSE']._serialized_start=377
  _globals['_INJECTMESSAGERESPONSE']._serialized_end=438
  _globals['_RUNQUERYREQUEST']._serialized_start=440
  _globals['_RUNQUERYREQUEST']._serialized_end=547
  _globals['_RUNQUERYRESPONSE']._serialized_start=549
  _globals['_RUNQUERYRESPONSE']._serialized_end=674
  _globals['_WORKERAPI']._serialized_start=677
  _globals['_WORKERAPI']._serialized_end=805
# @@protoc_insertion_point(module_scope)
